stages:
  - deploy
 
deploy_staging:
  stage: deploy
  only:
    - staging
  tags:
    - production
  script:
    - echo "Deploy Meditation Craft admin panel to staging server"
    - echo "running as $USER in $PWD HOME is $HOME"
    - . ~/.bashrc
    - nvm use v21
    - node --version
    - cp -v .env.staging .env.production
    - npm install --legacy-peer-deps
    - npm run build
    - PORT=50363 docker-compose -c staging up --build -d
  environment:
    name: staging
    url: https://admin-staging.meditationcrafts.com


deploy_production:
  stage: deploy
  only:
    - main
  tags:
    - production
  script:
    - echo "Deploy Meditation Craft admin panel to live server"
    - echo "running as $USER in $PWD HOME is $HOME"
    - . ~/.bashrc
    - nvm use v21
    - node --version
    - npm install
    - npm ci --cache .npm
    - npm run build
    - PORT=50363 docker-compose -c production up --build -d
  environment:
    name: production
    url: https://admin.meditationcrafts.com
